# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentFirstName', models.TextField()),
                ('studentLastName', models.TextField()),
                ('SATScore', models.IntegerField()),
                ('isArtistNomination', models.BooleanField()),
                ('isAcademicNomination', models.BooleanField()),
            ],
        ),
    ]
