# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominationapp', '0002_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='GPA',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
            preserve_default=False,
        ),
    ]
